services:
  db:
    image: postgres:17
    container_name: db
    ports:
      - "5433:5432"
    env_file:
      - .env

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
